export type CombatAction =
  | "stance"
  | "jab"
  | "cross"
  | "hook"
  | "uppercut"
  | "kick"
  | "block"
  | "parry"
  | "dodge"
  | "hit-reaction";

export type CombatSide = "left" | "right" | "center";

export interface CombatDirection {
  id: string;
  action: CombatAction;
  variant: string;
  name: string;
  thesis: string;
  side: CombatSide;
  duration: number;
  force: number;
  guard: number;
  commitment: number;
  asymmetry: number;
  overlapFrames: number;
  tags: string[];
}

type Seed = Omit<CombatDirection, "id" | "action">;

const groups: Record<CombatAction, Seed[]> = {
  stance: [
    { variant: "boxing", name: "Balanced Boxing Guard", thesis: "Compact orthodox base with chin protection, quiet weight changes and both hands ready without freezing the silhouette.", side: "right", duration: 1.8, force: 0.42, guard: 0.9, commitment: 0.35, asymmetry: 0.22, overlapFrames: 2, tags: ["orthodox", "boxing", "breathing"] },
    { variant: "peekaboo", name: "Peekaboo Pressure Guard", thesis: "Compressed high guard with rhythmic side slips and forward pressure that feels ready to explode from either hand.", side: "center", duration: 1.5, force: 0.65, guard: 1, commitment: 0.62, asymmetry: 0.12, overlapFrames: 1, tags: ["peekaboo", "pressure", "head-movement"] },
    { variant: "longguard", name: "Long Guard Range Trap", thesis: "Lead hand occupies space while the rear hand protects the jaw and the body quietly measures counterattack distance.", side: "left", duration: 2, force: 0.38, guard: 0.86, commitment: 0.32, asymmetry: 0.55, overlapFrames: 3, tags: ["long-guard", "range", "counter"] },
    { variant: "karate", name: "Bladed Karate Stance", thesis: "Narrow side-on silhouette stores linear acceleration in the rear leg while the lead hand controls the center line.", side: "right", duration: 1.9, force: 0.58, guard: 0.68, commitment: 0.56, asymmetry: 0.7, overlapFrames: 2, tags: ["karate", "bladed", "linear"] },
    { variant: "muaythai", name: "Heavy Muay Thai Base", thesis: "Tall planted posture keeps both forearms available for checks while restrained weight shifts communicate density and balance.", side: "center", duration: 1.7, force: 0.72, guard: 0.94, commitment: 0.5, asymmetry: 0.16, overlapFrames: 3, tags: ["muay-thai", "planted", "heavy"] },
    { variant: "street", name: "Deceptive Street Guard", thesis: "Hands begin deceptively low while uneven foot pressure and shoulder tension reveal an unpredictable ambush posture.", side: "left", duration: 2.1, force: 0.7, guard: 0.48, commitment: 0.52, asymmetry: 0.78, overlapFrames: 2, tags: ["street", "deceptive", "loose"] },
    { variant: "counter", name: "Patient Counter Fighter", thesis: "Almost motionless center lets the head make tiny threat reads while the rear side remains coiled for immediate punishment.", side: "right", duration: 2.2, force: 0.62, guard: 0.88, commitment: 0.38, asymmetry: 0.34, overlapFrames: 4, tags: ["counter", "patient", "coiled"] },
    { variant: "injured", name: "Wounded Defensive Guard", thesis: "The healthy side bears weight and shields the ribs while the injured side stays useful without pretending the pain disappeared.", side: "left", duration: 2.3, force: 0.34, guard: 0.95, commitment: 0.28, asymmetry: 0.9, overlapFrames: 3, tags: ["injured", "protective", "survival"] },
    { variant: "anime", name: "Anime Duel Stillness", thesis: "Graphic asymmetry and supernatural calm hold a readable threat line before sparse secondary motion breaks the stillness.", side: "right", duration: 2.4, force: 0.84, guard: 0.72, commitment: 0.68, asymmetry: 0.62, overlapFrames: 5, tags: ["anime", "duel", "stillness"] },
    { variant: "berserker", name: "Berserker Forward Hunch", thesis: "Open reckless guard, forward-loaded feet and impatient shoulder pulses communicate aggression that sacrifices defense.", side: "center", duration: 1.35, force: 0.94, guard: 0.28, commitment: 0.92, asymmetry: 0.44, overlapFrames: 1, tags: ["berserker", "reckless", "pressure"] },
  ],
  jab: [
    { variant: "snap", name: "Sharp Measuring Jab", thesis: "A short lead-hand snap tests distance with almost no tell and returns to the jaw before the torso overcommits.", side: "left", duration: 0.38, force: 0.5, guard: 0.92, commitment: 0.42, asymmetry: 0.48, overlapFrames: 1, tags: ["boxing", "range", "snap"] },
    { variant: "stiff", name: "Stiff Intercepting Jab", thesis: "A planted lead shoulder drives through an advancing target while the rear hand and base stay defensively responsible.", side: "left", duration: 0.46, force: 0.75, guard: 0.9, commitment: 0.65, asymmetry: 0.45, overlapFrames: 2, tags: ["intercept", "stiff", "planted"] },
    { variant: "step", name: "Step-In Pressure Jab", thesis: "Lead foot and fist claim range together, moving the entire body behind the strike instead of reaching with the arm alone.", side: "left", duration: 0.5, force: 0.7, guard: 0.82, commitment: 0.78, asymmetry: 0.52, overlapFrames: 2, tags: ["step-in", "pressure", "linear"] },
    { variant: "body", name: "Level-Change Body Jab", thesis: "The center drops before the lead fist attacks the body line while the head remains outside the likely counter path.", side: "left", duration: 0.52, force: 0.64, guard: 0.84, commitment: 0.7, asymmetry: 0.6, overlapFrames: 2, tags: ["body-shot", "level-change", "outside-head"] },
    { variant: "flicker", name: "Loose Flicker Jab", thesis: "A low loose lead hand whips upward from an unusual line and retracts with delayed shoulder relaxation.", side: "left", duration: 0.34, force: 0.42, guard: 0.56, commitment: 0.38, asymmetry: 0.72, overlapFrames: 3, tags: ["flicker", "loose", "unorthodox"] },
    { variant: "power", name: "Power Jab With Rear Drive", thesis: "Rear-leg pressure shifts the torso forward and turns a lead straight into a compact power shot with visible recovery cost.", side: "left", duration: 0.56, force: 0.84, guard: 0.78, commitment: 0.86, asymmetry: 0.5, overlapFrames: 2, tags: ["power", "rear-drive", "heavy"] },
    { variant: "retreat", name: "Retreating Check Jab", thesis: "The body gives ground while the lead arm interrupts pursuit, keeping the chest oriented toward the threat throughout.", side: "left", duration: 0.48, force: 0.46, guard: 0.94, commitment: 0.34, asymmetry: 0.58, overlapFrames: 2, tags: ["retreat", "check", "defensive"] },
    { variant: "southpaw", name: "Southpaw Right Jab", thesis: "Mirrored lead-side mechanics make the right arm the true striker while the left hand protects and stores the cross.", side: "right", duration: 0.4, force: 0.56, guard: 0.9, commitment: 0.5, asymmetry: 0.5, overlapFrames: 1, tags: ["southpaw", "snap", "mirrored"] },
    { variant: "anime", name: "Anime Vanishing Jab", thesis: "A readable held guard releases into a nearly instantaneous straight line, then leaves a deliberately delayed body recovery.", side: "left", duration: 0.3, force: 0.92, guard: 0.82, commitment: 0.74, asymmetry: 0.52, overlapFrames: 4, tags: ["anime", "speed", "held-release"] },
    { variant: "exhausted", name: "Exhausted Survival Jab", thesis: "A tired lead hand still finds the target but dropped posture and a slow imperfect return preserve believable fatigue.", side: "left", duration: 0.68, force: 0.38, guard: 0.72, commitment: 0.48, asymmetry: 0.66, overlapFrames: 4, tags: ["exhausted", "imperfect", "survival"] },
  ],
  cross: [
    { variant: "classic", name: "Orthodox Rear Cross", thesis: "Rear foot, hip, torso and right fist arrive as one kinetic chain while the lead hand remains accountable for defense.", side: "right", duration: 0.52, force: 0.82, guard: 0.82, commitment: 0.82, asymmetry: 0.56, overlapFrames: 2, tags: ["boxing", "rear-hand", "kinetic-chain"] },
    { variant: "counter", name: "Slip Counter Cross", thesis: "The head leaves the center line during the load and the rear hand fires through the opening created by the slip.", side: "right", duration: 0.48, force: 0.86, guard: 0.86, commitment: 0.78, asymmetry: 0.68, overlapFrames: 2, tags: ["counter", "slip", "outside-head"] },
    { variant: "overhand", name: "Heavy Overhand Right", thesis: "The fist travels over a high guard on a descending arc with major torso tilt and a costly committed recovery.", side: "right", duration: 0.66, force: 1, guard: 0.58, commitment: 1, asymmetry: 0.72, overlapFrames: 3, tags: ["overhand", "descending", "heavy"] },
    { variant: "body", name: "Rear Straight To Body", thesis: "A compact level change aligns the rear fist with the torso target while the lead shoulder and head stay protected.", side: "right", duration: 0.58, force: 0.78, guard: 0.84, commitment: 0.8, asymmetry: 0.62, overlapFrames: 2, tags: ["body-shot", "level-change", "straight"] },
    { variant: "lunging", name: "Long Lunging Cross", thesis: "A deep range-closing step stretches the rear straight into maximum reach while preserving a single forward force line.", side: "right", duration: 0.62, force: 0.9, guard: 0.68, commitment: 0.98, asymmetry: 0.58, overlapFrames: 3, tags: ["lunge", "long-range", "linear"] },
    { variant: "short", name: "Short Inside Cross", thesis: "Minimal windup and tight torso rotation deliver force at clinch range without turning the arm into a wide swing.", side: "right", duration: 0.4, force: 0.72, guard: 0.9, commitment: 0.62, asymmetry: 0.5, overlapFrames: 1, tags: ["inside", "compact", "no-tell"] },
    { variant: "stepthrough", name: "Step-Through Rear Straight", thesis: "The rear side continues past impact into a stance switch, making the strike a committed entry rather than a reset.", side: "right", duration: 0.72, force: 0.92, guard: 0.7, commitment: 1, asymmetry: 0.7, overlapFrames: 3, tags: ["step-through", "stance-switch", "entry"] },
    { variant: "southpaw", name: "Southpaw Left Cross", thesis: "Mirrored rear-hand mechanics drive the left fist from a southpaw base with clear right-hand guard responsibility.", side: "left", duration: 0.52, force: 0.84, guard: 0.84, commitment: 0.84, asymmetry: 0.56, overlapFrames: 2, tags: ["southpaw", "rear-hand", "mirrored"] },
    { variant: "anime", name: "Anime Armor-Break Cross", thesis: "A prolonged compressed load detonates into a short brutal impact hold followed by staggered whole-body recoil.", side: "right", duration: 0.58, force: 1, guard: 0.62, commitment: 1, asymmetry: 0.64, overlapFrames: 5, tags: ["anime", "armor-break", "impact-hold"] },
    { variant: "desperate", name: "Desperate Falling Cross", thesis: "Balance intentionally breaks forward so the fist lands before the body catches itself in an unstable survival recovery.", side: "right", duration: 0.7, force: 0.88, guard: 0.42, commitment: 1, asymmetry: 0.82, overlapFrames: 2, tags: ["desperate", "falling", "unstable"] },
  ],
  hook: [
    { variant: "lead", name: "Compact Lead Hook", thesis: "Lead hip and torso turn a short left-arm arc through the target while the rear hand stays fixed near the jaw.", side: "left", duration: 0.5, force: 0.78, guard: 0.88, commitment: 0.76, asymmetry: 0.64, overlapFrames: 2, tags: ["boxing", "compact", "horizontal-arc"] },
    { variant: "rear", name: "Heavy Rear Hook", thesis: "A larger right-side rotation sacrifices speed for mass, with the support leg visibly receiving the follow-through.", side: "right", duration: 0.62, force: 0.94, guard: 0.7, commitment: 0.94, asymmetry: 0.68, overlapFrames: 3, tags: ["rear-hand", "heavy", "horizontal-arc"] },
    { variant: "check", name: "Check Hook Exit", thesis: "The lead hook turns the opponent while the body pivots away, combining impact and lateral escape in one readable action.", side: "left", duration: 0.58, force: 0.72, guard: 0.86, commitment: 0.7, asymmetry: 0.76, overlapFrames: 3, tags: ["check-hook", "pivot", "exit"] },
    { variant: "body", name: "Digging Body Hook", thesis: "A deep level change and side crunch aim the hook into the ribs before the body rises back behind its guard.", side: "left", duration: 0.6, force: 0.86, guard: 0.8, commitment: 0.88, asymmetry: 0.72, overlapFrames: 2, tags: ["body-shot", "level-change", "digging"] },
    { variant: "shovel", name: "Shovel Hook Hybrid", thesis: "The striking arm travels on a diagonal between hook and uppercut while a short hip scoop supplies the force.", side: "right", duration: 0.55, force: 0.84, guard: 0.78, commitment: 0.82, asymmetry: 0.66, overlapFrames: 2, tags: ["shovel-hook", "diagonal-arc", "inside"] },
    { variant: "gazelle", name: "Leaping Gazelle Hook", thesis: "A compressed launch carries the lead hook forward through the air before a controlled asymmetric landing.", side: "left", duration: 0.76, force: 0.96, guard: 0.58, commitment: 1, asymmetry: 0.78, overlapFrames: 4, tags: ["gazelle", "leap", "long-range"] },
    { variant: "spinning", name: "Spinning Backfist Arc", thesis: "Head spotting, torso rotation and the trailing right arm create a full turning strike rather than an isolated arm sweep.", side: "right", duration: 0.78, force: 0.92, guard: 0.44, commitment: 1, asymmetry: 0.86, overlapFrames: 4, tags: ["spin", "backfist", "full-turn"] },
    { variant: "smothered", name: "Smothered Clinch Hook", thesis: "At extremely close range the torso makes a dense short rotation and the arm stays compact instead of clipping outward.", side: "right", duration: 0.44, force: 0.7, guard: 0.9, commitment: 0.66, asymmetry: 0.6, overlapFrames: 1, tags: ["clinch", "compact", "inside"] },
    { variant: "anime", name: "Anime Crescent Hook", thesis: "A broad graphic windup compresses into a fast crescent silhouette with a one-frame impact accent and long trailing settle.", side: "left", duration: 0.64, force: 1, guard: 0.5, commitment: 1, asymmetry: 0.82, overlapFrames: 5, tags: ["anime", "crescent", "impact-accent"] },
    { variant: "wounded", name: "One-Sided Wounded Hook", thesis: "The healthy side generates a rough hook while the painful side protects the body and limits rotational follow-through.", side: "right", duration: 0.68, force: 0.66, guard: 0.84, commitment: 0.72, asymmetry: 0.92, overlapFrames: 3, tags: ["injured", "protective", "limited-turn"] },
  ],
  uppercut: [
    { variant: "lead", name: "Short Lead Uppercut", thesis: "A small compression and left-side hip rise drive a compact vertical strike suited to close boxing range.", side: "left", duration: 0.5, force: 0.74, guard: 0.88, commitment: 0.74, asymmetry: 0.62, overlapFrames: 2, tags: ["boxing", "compact", "rising-arc"] },
    { variant: "rear", name: "Rear Power Uppercut", thesis: "The right side loads deeper and rises through the target with the legs and torso visibly supporting the arm.", side: "right", duration: 0.62, force: 0.94, guard: 0.76, commitment: 0.94, asymmetry: 0.68, overlapFrames: 3, tags: ["rear-hand", "power", "rising-arc"] },
    { variant: "body", name: "Body-Line Uppercut", thesis: "A low compact scoop attacks beneath the ribs without the exaggerated vertical launch of a chin-targeting uppercut.", side: "right", duration: 0.54, force: 0.8, guard: 0.84, commitment: 0.8, asymmetry: 0.64, overlapFrames: 2, tags: ["body-shot", "low-line", "compact"] },
    { variant: "counter", name: "Slip Inside Uppercut", thesis: "The head slips outside an incoming straight and the near hand rises immediately through the newly opened center.", side: "left", duration: 0.48, force: 0.82, guard: 0.9, commitment: 0.76, asymmetry: 0.72, overlapFrames: 2, tags: ["counter", "slip", "inside"] },
    { variant: "long", name: "Long Rising Uppercut", thesis: "A forward step extends the rising fist beyond normal pocket range while the torso stays behind the force line.", side: "right", duration: 0.64, force: 0.88, guard: 0.7, commitment: 0.94, asymmetry: 0.66, overlapFrames: 3, tags: ["long-range", "step-in", "rising-arc"] },
    { variant: "doubleload", name: "Double-Level Power Load", thesis: "A pronounced two-stage compression telegraphs enormous force before the rear uppercut releases explosively.", side: "right", duration: 0.76, force: 1, guard: 0.62, commitment: 1, asymmetry: 0.7, overlapFrames: 4, tags: ["double-load", "telegraphed", "finisher"] },
    { variant: "shovel", name: "Diagonal Shovel Uppercut", thesis: "The fist climbs diagonally around a tight guard while torso roll distinguishes the trajectory from a straight punch.", side: "left", duration: 0.56, force: 0.84, guard: 0.8, commitment: 0.84, asymmetry: 0.7, overlapFrames: 2, tags: ["shovel", "diagonal-arc", "guard-gap"] },
    { variant: "leaping", name: "Leaping Dragon Uppercut", thesis: "A deep crouch launches the whole R6 silhouette upward so the arm reads as the tip of a body-driven ascent.", side: "right", duration: 0.82, force: 1, guard: 0.5, commitment: 1, asymmetry: 0.76, overlapFrames: 4, tags: ["leap", "launcher", "whole-body"] },
    { variant: "anime", name: "Anime Skybreaker Uppercut", thesis: "Extreme hold, sudden vertical release and suspended follow-through create a cinematic launcher without fake elbow bending.", side: "right", duration: 0.7, force: 1, guard: 0.48, commitment: 1, asymmetry: 0.8, overlapFrames: 5, tags: ["anime", "launcher", "impact-hold"] },
    { variant: "exhausted", name: "Last-Energy Uppercut", thesis: "A tired fighter spends the remaining leg drive on one rising punch and visibly struggles to recover balance afterward.", side: "left", duration: 0.82, force: 0.72, guard: 0.58, commitment: 0.9, asymmetry: 0.84, overlapFrames: 4, tags: ["exhausted", "last-effort", "unstable"] },
  ],
  kick: [
    { variant: "front", name: "Snapping Front Kick", thesis: "The support side braces while the entire R6 leg snaps forward on a direct line and retracts before posture opens.", side: "right", duration: 0.62, force: 0.76, guard: 0.9, commitment: 0.7, asymmetry: 0.62, overlapFrames: 2, tags: ["front-kick", "linear", "retract"] },
    { variant: "push", name: "Driving Push Kick", thesis: "A longer chamber-like body compression projects the rigid leg and torso together to create space rather than whip.", side: "left", duration: 0.72, force: 0.88, guard: 0.86, commitment: 0.88, asymmetry: 0.66, overlapFrames: 3, tags: ["push-kick", "space-making", "driving"] },
    { variant: "roundhouse", name: "Rear Roundhouse Kick", thesis: "Support pivot, hip turn and a wide right-leg arc produce the strike while the arms counterbalance the rotation.", side: "right", duration: 0.78, force: 0.94, guard: 0.68, commitment: 0.96, asymmetry: 0.76, overlapFrames: 3, tags: ["roundhouse", "pivot", "horizontal-arc"] },
    { variant: "low", name: "Heavy Low Kick", thesis: "A compact hip rotation sends the rear leg through a low target and recovers into a stable fighting base.", side: "right", duration: 0.66, force: 0.9, guard: 0.8, commitment: 0.86, asymmetry: 0.7, overlapFrames: 2, tags: ["low-kick", "muay-thai", "compact"] },
    { variant: "side", name: "Long Side Kick", thesis: "The body turns side-on and drives the lead leg along a straight horizontal line with the head watching over the shoulder.", side: "left", duration: 0.8, force: 0.9, guard: 0.7, commitment: 0.94, asymmetry: 0.84, overlapFrames: 3, tags: ["side-kick", "bladed", "long-range"] },
    { variant: "back", name: "Spinning Back Kick", thesis: "Head spots first, torso coils through a turn and the rear leg becomes a direct thrust at the end of the rotation.", side: "right", duration: 0.92, force: 1, guard: 0.42, commitment: 1, asymmetry: 0.9, overlapFrames: 4, tags: ["back-kick", "spin", "spotting"] },
    { variant: "axe", name: "Descending Axe Kick", thesis: "The leg rises with a tall silhouette then cuts downward as the torso counterbalances the vertical striking path.", side: "right", duration: 0.94, force: 0.92, guard: 0.56, commitment: 0.96, asymmetry: 0.82, overlapFrames: 4, tags: ["axe-kick", "descending", "vertical-arc"] },
    { variant: "hook", name: "Turning Hook Kick", thesis: "A side-on extension sweeps across the target late in the turn, distinguished from a roundhouse by its returning arc.", side: "left", duration: 0.9, force: 0.88, guard: 0.5, commitment: 1, asymmetry: 0.88, overlapFrames: 4, tags: ["hook-kick", "returning-arc", "spin"] },
    { variant: "flying", name: "Flying Anime Kick", thesis: "A readable takeoff compresses into a long airborne attack line before the limbs reorganize for an asymmetric landing.", side: "right", duration: 1.02, force: 1, guard: 0.38, commitment: 1, asymmetry: 0.84, overlapFrames: 5, tags: ["anime", "flying-kick", "airborne"] },
    { variant: "wounded", name: "Healthy-Leg Survival Kick", thesis: "The uninjured leg attacks from a guarded lean while the painful support forces an abbreviated, imperfect recovery.", side: "right", duration: 0.88, force: 0.66, guard: 0.84, commitment: 0.74, asymmetry: 0.94, overlapFrames: 3, tags: ["injured", "survival", "imperfect"] },
  ],
  block: [
    { variant: "high", name: "Compact High Cover", thesis: "Both rigid R6 arms form a tight roof around the head while the torso compresses behind the structure.", side: "center", duration: 0.5, force: 0.52, guard: 1, commitment: 0.58, asymmetry: 0.16, overlapFrames: 1, tags: ["high-block", "shell", "compact"] },
    { variant: "left", name: "Left Temple Shield", thesis: "The left arm and shoulder close one side of the head while the opposite hand remains ready to counter.", side: "left", duration: 0.44, force: 0.48, guard: 0.98, commitment: 0.5, asymmetry: 0.72, overlapFrames: 2, tags: ["side-block", "left-cover", "counter-ready"] },
    { variant: "right", name: "Right Temple Shield", thesis: "The right arm absorbs the high line with a small body turn that redirects force instead of presenting a flat target.", side: "right", duration: 0.44, force: 0.48, guard: 0.98, commitment: 0.5, asymmetry: 0.72, overlapFrames: 2, tags: ["side-block", "right-cover", "redirect"] },
    { variant: "body", name: "Elbow-Line Body Cover", thesis: "The entire forearmless R6 arm drops as one unit to protect the ribs while the torso crunch carries the defensive idea.", side: "left", duration: 0.5, force: 0.5, guard: 0.96, commitment: 0.56, asymmetry: 0.7, overlapFrames: 2, tags: ["body-block", "r6-honest", "crunch"] },
    { variant: "cross", name: "Crossed Forearm Guard", thesis: "Both arms cross into a broad emergency shield and the lower body braces against a powerful frontal impact.", side: "center", duration: 0.58, force: 0.72, guard: 1, commitment: 0.74, asymmetry: 0.12, overlapFrames: 2, tags: ["cross-block", "frontal", "brace"] },
    { variant: "low", name: "Low-Line Leg Shield", thesis: "One rigid leg lifts across the low line while arms and torso counterbalance the temporary loss of support.", side: "right", duration: 0.64, force: 0.6, guard: 0.9, commitment: 0.66, asymmetry: 0.82, overlapFrames: 3, tags: ["leg-block", "low-line", "balance"] },
    { variant: "shoulder", name: "Shoulder Roll Defense", thesis: "The torso rotates behind a raised lead shoulder so a straight attack glances past while the rear hand stays home.", side: "left", duration: 0.46, force: 0.44, guard: 0.94, commitment: 0.48, asymmetry: 0.74, overlapFrames: 2, tags: ["shoulder-roll", "glance", "counter"] },
    { variant: "absorb", name: "Heavy Absorption Guard", thesis: "A planted shell receives a large impact, then weight and arms settle on staggered timings to communicate force.", side: "center", duration: 0.76, force: 0.82, guard: 1, commitment: 0.84, asymmetry: 0.24, overlapFrames: 4, tags: ["heavy", "absorb", "impact-recoil"] },
    { variant: "anime", name: "Anime One-Arm Stop", thesis: "One arm meets an overwhelming strike in a graphic held silhouette while the rest of the body ripples from impact.", side: "right", duration: 0.7, force: 0.92, guard: 0.86, commitment: 0.9, asymmetry: 0.88, overlapFrames: 5, tags: ["anime", "one-arm", "impact-hold"] },
    { variant: "desperate", name: "Desperate Collapsing Cover", thesis: "A late improvised shell protects the head but balance and posture collapse under pressure instead of looking invulnerable.", side: "center", duration: 0.82, force: 0.64, guard: 0.92, commitment: 0.76, asymmetry: 0.5, overlapFrames: 3, tags: ["desperate", "late", "collapse"] },
  ],
  parry: [
    { variant: "outside", name: "Outside Lead-Hand Parry", thesis: "A tiny lead-hand deflection clears the center line while the torso stays quiet enough for an immediate counter.", side: "left", duration: 0.36, force: 0.38, guard: 0.94, commitment: 0.3, asymmetry: 0.7, overlapFrames: 1, tags: ["outside-parry", "minimal", "counter-ready"] },
    { variant: "inside", name: "Inside Rear-Hand Parry", thesis: "The rear hand redirects an incoming straight inward with a short precise action that never becomes a slap.", side: "right", duration: 0.38, force: 0.42, guard: 0.92, commitment: 0.34, asymmetry: 0.68, overlapFrames: 1, tags: ["inside-parry", "precise", "rear-hand"] },
    { variant: "down", name: "Downward Body-Line Parry", thesis: "A compact hand drop removes a body attack from its path while the head and opposite guard remain disciplined.", side: "left", duration: 0.4, force: 0.44, guard: 0.94, commitment: 0.38, asymmetry: 0.72, overlapFrames: 2, tags: ["down-parry", "body-line", "disciplined"] },
    { variant: "cross", name: "Cross-Hand Catch And Clear", thesis: "The opposite hand crosses the center to catch and redirect, creating visible rotational preparation for a return strike.", side: "right", duration: 0.48, force: 0.5, guard: 0.86, commitment: 0.5, asymmetry: 0.82, overlapFrames: 2, tags: ["cross-parry", "catch", "counter-load"] },
    { variant: "double", name: "Two-Beat Double Parry", thesis: "Two separate economical deflections answer a quick pair of attacks without merging into random arm waving.", side: "center", duration: 0.62, force: 0.5, guard: 0.96, commitment: 0.52, asymmetry: 0.42, overlapFrames: 1, tags: ["double-parry", "two-beat", "rhythmic"] },
    { variant: "scoop", name: "Low Scoop Parry", thesis: "The hand and torso make a small rising scoop that carries a low attack past the body and opens the center.", side: "right", duration: 0.46, force: 0.48, guard: 0.9, commitment: 0.46, asymmetry: 0.76, overlapFrames: 2, tags: ["scoop-parry", "low-line", "opening"] },
    { variant: "retreat", name: "Retreating Range Parry", thesis: "A backward weight shift lengthens the reaction window while the lead hand barely alters the incoming line.", side: "left", duration: 0.5, force: 0.36, guard: 0.96, commitment: 0.32, asymmetry: 0.64, overlapFrames: 2, tags: ["retreat", "range", "soft-touch"] },
    { variant: "hard", name: "Hard Smashing Parry", thesis: "A forceful whole-side deflection punishes the attacking limb, visibly different from the economical technical parries.", side: "right", duration: 0.54, force: 0.8, guard: 0.82, commitment: 0.72, asymmetry: 0.8, overlapFrames: 3, tags: ["hard-parry", "smash", "whole-side"] },
    { variant: "anime", name: "Anime Invisible Deflection", thesis: "Near-still guard produces a tiny ultra-fast contact accent followed by delayed clothing-like arm settlement.", side: "left", duration: 0.32, force: 0.84, guard: 0.92, commitment: 0.4, asymmetry: 0.72, overlapFrames: 5, tags: ["anime", "speed", "micro-action"] },
    { variant: "tired", name: "Late Fatigued Parry", thesis: "A slow reaction barely redirects the attack and leaves the arm displaced, preserving the cost of exhaustion.", side: "right", duration: 0.68, force: 0.34, guard: 0.72, commitment: 0.48, asymmetry: 0.84, overlapFrames: 4, tags: ["exhausted", "late", "imperfect"] },
  ],
  dodge: [
    { variant: "outside-slip", name: "Outside Head Slip", thesis: "The head and torso leave the center just enough to evade a straight while the feet and guard remain counter-ready.", side: "left", duration: 0.46, force: 0.46, guard: 0.94, commitment: 0.48, asymmetry: 0.72, overlapFrames: 2, tags: ["slip", "outside", "counter-ready"] },
    { variant: "inside-slip", name: "Inside Head Slip", thesis: "A compact opposite-side slip threads inside the attack with visible risk and a coiled rear-hand counter position.", side: "right", duration: 0.44, force: 0.5, guard: 0.9, commitment: 0.52, asymmetry: 0.74, overlapFrames: 2, tags: ["slip", "inside", "coiled"] },
    { variant: "pull", name: "Pull Counter Lean", thesis: "The head retreats beyond the strike without moving the whole body away, then posture rebounds into range.", side: "center", duration: 0.5, force: 0.44, guard: 0.88, commitment: 0.42, asymmetry: 0.3, overlapFrames: 2, tags: ["pull", "counter", "rebound"] },
    { variant: "duck", name: "Compact Duck Under", thesis: "The center drops vertically beneath a high attack while guard and gaze stay organized for the exit.", side: "center", duration: 0.56, force: 0.54, guard: 0.94, commitment: 0.6, asymmetry: 0.24, overlapFrames: 2, tags: ["duck", "level-change", "high-attack"] },
    { variant: "roll-left", name: "Left Weave And Roll", thesis: "The torso traces a clear low U-shaped path under a hook and rises on the left in counter position.", side: "left", duration: 0.64, force: 0.62, guard: 0.9, commitment: 0.68, asymmetry: 0.78, overlapFrames: 3, tags: ["weave", "u-path", "left-exit"] },
    { variant: "roll-right", name: "Right Weave And Roll", thesis: "A mirrored low arc carries the head under the attack and restores balance on the right side.", side: "right", duration: 0.64, force: 0.62, guard: 0.9, commitment: 0.68, asymmetry: 0.78, overlapFrames: 3, tags: ["weave", "u-path", "right-exit"] },
    { variant: "sidestep", name: "Angle-Creating Sidestep", thesis: "A lateral weight cut moves the whole body off line while the chest keeps tracking the opponent.", side: "left", duration: 0.58, force: 0.68, guard: 0.88, commitment: 0.72, asymmetry: 0.82, overlapFrames: 2, tags: ["sidestep", "angle", "track-target"] },
    { variant: "backstep", name: "Fast Backstep Evade", thesis: "The lower body throws range backward while the upper body stays ready instead of flailing into a retreat run pose.", side: "center", duration: 0.52, force: 0.72, guard: 0.92, commitment: 0.62, asymmetry: 0.34, overlapFrames: 2, tags: ["backstep", "range", "guarded"] },
    { variant: "anime", name: "Anime Afterimage Sway", thesis: "A held silhouette breaks into a sharp lateral displacement with the head arriving first and limbs settling last.", side: "right", duration: 0.36, force: 0.94, guard: 0.78, commitment: 0.74, asymmetry: 0.88, overlapFrames: 5, tags: ["anime", "afterimage", "sharp"] },
    { variant: "desperate", name: "Desperate Stumble Evade", thesis: "The attack misses because balance breaks unpredictably, then the fighter scrambles back into a usable guard.", side: "left", duration: 0.76, force: 0.58, guard: 0.62, commitment: 0.84, asymmetry: 0.94, overlapFrames: 2, tags: ["desperate", "stumble", "recovery"] },
  ],
  "hit-reaction": [
    { variant: "face-light", name: "Light Face Snap", thesis: "The head leads a small sharp turn and the torso follows later, communicating contact without theatrical full-body collapse.", side: "left", duration: 0.46, force: 0.4, guard: 0.3, commitment: 0.38, asymmetry: 0.66, overlapFrames: 3, tags: ["face-hit", "light", "head-led"] },
    { variant: "face-heavy", name: "Heavy Cross Face Reaction", thesis: "Head rotation, shoulder displacement and a delayed balance catch sell a powerful lateral strike to the jaw.", side: "right", duration: 0.72, force: 0.86, guard: 0.18, commitment: 0.84, asymmetry: 0.8, overlapFrames: 4, tags: ["face-hit", "heavy", "balance-catch"] },
    { variant: "body", name: "Compressed Body Shot Reaction", thesis: "Breath and posture collapse toward the struck ribs before the arms instinctively close around the injury.", side: "left", duration: 0.82, force: 0.72, guard: 0.24, commitment: 0.76, asymmetry: 0.78, overlapFrames: 4, tags: ["body-hit", "compression", "protective"] },
    { variant: "uppercut", name: "Chin Lift Reaction", thesis: "The head and chest rise sharply from an upward impact while the legs lag before catching the center.", side: "center", duration: 0.68, force: 0.82, guard: 0.16, commitment: 0.78, asymmetry: 0.38, overlapFrames: 4, tags: ["uppercut-hit", "lift", "delayed-legs"] },
    { variant: "lowkick", name: "Low Kick Buckle", thesis: "The struck leg loses support and the torso shifts urgently to the healthy side instead of merely rotating in place.", side: "right", duration: 0.8, force: 0.76, guard: 0.3, commitment: 0.82, asymmetry: 0.9, overlapFrames: 3, tags: ["leg-hit", "buckle", "support-loss"] },
    { variant: "push", name: "Chest Pushback Reaction", thesis: "The sternum receives a direct force line and the feet brace late, creating staged backward recoil without a fall.", side: "center", duration: 0.72, force: 0.7, guard: 0.26, commitment: 0.72, asymmetry: 0.28, overlapFrames: 3, tags: ["chest-hit", "pushback", "brace"] },
    { variant: "spin", name: "Rotational Stagger Hit", thesis: "An off-center impact turns the torso first and drags the limbs into a staggered half-spin recovery.", side: "left", duration: 0.9, force: 0.88, guard: 0.14, commitment: 0.94, asymmetry: 0.88, overlapFrames: 5, tags: ["rotational-hit", "stagger", "half-spin"] },
    { variant: "knockdown", name: "Hard Knockdown Start", thesis: "The center is displaced beyond the support base and the body begins a believable fall rather than returning upright.", side: "center", duration: 1.02, force: 1, guard: 0.08, commitment: 1, asymmetry: 0.66, overlapFrames: 4, tags: ["knockdown", "fall", "no-recovery"] },
    { variant: "anime", name: "Anime Delayed Impact Reaction", thesis: "A tiny contact hold precedes an explosive full-body recoil, using contrast rather than constant motion to sell power.", side: "right", duration: 0.78, force: 1, guard: 0.1, commitment: 1, asymmetry: 0.82, overlapFrames: 5, tags: ["anime", "delayed-impact", "explosive"] },
    { variant: "resist", name: "Supreme Fighter Resists Hit", thesis: "The head and shoulder acknowledge enormous contact but the planted base absorbs it and deliberately refuses displacement.", side: "left", duration: 0.7, force: 0.94, guard: 0.42, commitment: 0.64, asymmetry: 0.74, overlapFrames: 4, tags: ["resist", "planted", "supreme"] },
  ],
};

const actionOrder = Object.keys(groups) as CombatAction[];

export const combatDirections: CombatDirection[] = actionOrder.flatMap((action) =>
  groups[action].map((seed, index) => ({
    ...seed,
    action,
    id: `${action.replace(/[^a-z]/g, "")}-${String(index + 1).padStart(2, "0")}`,
  })),
);

export function combatDirectionsFor(action: CombatAction): CombatDirection[] {
  return combatDirections.filter((direction) => direction.action === action);
}
